-- Database: bloggers
-- DROP DATABASE IF EXISTS bloggers;
CREATE DATABASE bloggers WITH OWNER = postgres ENCODING = 'UTF8' LC_COLLATE = 'en_US.utf8' LC_CTYPE = 'en_US.utf8' TABLESPACE = pg_default CONNECTION
LIMIT
    = -1 IS_TEMPLATE = False;

GRANT TEMPORARY,
CONNECT ON DATABASE bloggers TO PUBLIC;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";